<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Factures: the providers whose bills a courier pays (or mandats sends)
 * on a client's behalf, and the bill details on an order.
 */
final class Version20260929132717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Bill providers (seeded with STEG, SONEDE, Tunisie Telecom, Topnet, IZI, Wafa Cash) and Factures order fields';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE bill_provider (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, kind VARCHAR(20) NOT NULL, logo_filename VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F38BD5D5E237E06 ON bill_provider (name)');
        $this->addSql('ALTER TABLE "order" ADD bill_reference VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE "order" ADD bill_amount NUMERIC(10, 3) DEFAULT NULL');
        $this->addSql('ALTER TABLE "order" ADD bill_photo_filename VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "order" ADD bill_provider_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993987B4C10A7 FOREIGN KEY (bill_provider_id) REFERENCES bill_provider (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F52993987B4C10A7 ON "order" (bill_provider_id)');

        // The providers the client asked for; logos are uploaded from the
        // admin dashboard (Bill providers page).
        $providers = [
            ['STEG', 'BILL'],
            ['SONEDE', 'BILL'],
            ['Tunisie Telecom', 'BILL'],
            ['Topnet', 'BILL'],
            ['IZI – Banque Zitouna', 'TRANSFER'],
            ['Wafa Cash', 'TRANSFER'],
        ];

        foreach ($providers as $position => [$name, $kind]) {
            $this->addSql(
                'INSERT INTO bill_provider (name, kind, is_active, position, created_at, updated_at) VALUES (:name, :kind, true, :position, NOW(), NOW())',
                ['name' => $name, 'kind' => $kind, 'position' => $position + 1]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993987B4C10A7');
        $this->addSql('DROP INDEX IDX_F52993987B4C10A7');
        $this->addSql('ALTER TABLE "order" DROP bill_reference');
        $this->addSql('ALTER TABLE "order" DROP bill_amount');
        $this->addSql('ALTER TABLE "order" DROP bill_photo_filename');
        $this->addSql('ALTER TABLE "order" DROP bill_provider_id');
        $this->addSql('DROP TABLE bill_provider');
    }
}
