<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909170353 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE delivery_zone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, fee NUMERIC(10, 3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7177089D5E237E06 ON delivery_zone (name)');
        $this->addSql('ALTER TABLE "order" ADD delivery_fee NUMERIC(10, 3) NOT NULL');
        $this->addSql('ALTER TABLE "order" ADD delivery_zone_id INT NOT NULL');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F529939895328075 FOREIGN KEY (delivery_zone_id) REFERENCES delivery_zone (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F529939895328075 ON "order" (delivery_zone_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE delivery_zone');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F529939895328075');
        $this->addSql('DROP INDEX IDX_F529939895328075');
        $this->addSql('ALTER TABLE "order" DROP delivery_fee');
        $this->addSql('ALTER TABLE "order" DROP delivery_zone_id');
    }
}
