<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260913143307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add promotion table and courier_location table (last known GPS position)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE courier_location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, courier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AE7301FAE3D8151C ON courier_location (courier_id)');
        $this->addSql('CREATE TABLE promotion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, image_filename VARCHAR(255) DEFAULT NULL, discount_type VARCHAR(20) NOT NULL, discount_value NUMERIC(10, 3) NOT NULL, promo_code VARCHAR(50) DEFAULT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, restaurant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C11D7DD1B1E7706E ON promotion (restaurant_id)');
        $this->addSql('ALTER TABLE courier_location ADD CONSTRAINT FK_AE7301FAE3D8151C FOREIGN KEY (courier_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promotion ADD CONSTRAINT FK_C11D7DD1B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE courier_location DROP CONSTRAINT FK_AE7301FAE3D8151C');
        $this->addSql('ALTER TABLE promotion DROP CONSTRAINT FK_C11D7DD1B1E7706E');
        $this->addSql('DROP TABLE courier_location');
        $this->addSql('DROP TABLE promotion');
    }
}
